### PR TITLE
Add prefix option for incrementor

### PR DESCRIPTION
**Pull request by mattxgreen**
For my use case I want to be able to have a prefix on the document. I have made the adjustments necessary, with no effect on the original functionality.  

Thank you for making this package available.

### CODE REVIEW

**Comment by r3wt** [comment]
ill try to get to this in the evening. working on a damn cadillac atm

**Comment by mattxgreen** [comment]
Sorry, I commented out the console.logs after the request. I thought the PR would retain the original sha. I can revert, if you prefer the logs.

**Comment by r3wt** [comment]
i dont care. but, just be wary with this package, deleting documents seems to cause index errors that in turn break the functionality of the library. i forked it from another package in hopes to fix it but never did

On Jun 16, 2018 2:47 PM, Matt Green <notifications@github.com> wrote:

Sorry, I commented out the console.logs after the request. I thought the PR would retain the original sha. I can revert, if you prefer the logs.

**Comment by r3wt** [comment]
merged

**Comment by mattxgreen** [comment]
Awesome, thanks! Is npm updated?

**Comment by r3wt** [comment]
Good catch. my apologies, i forgot. ill get to it when i get home and ill announce it here. Thanks

On Jun 16, 2018 4:55 PM, Matt Green <notifications@github.com> wrote:

Awesome, thanks! Is npm updated?

**Pull request merged**
